### ISSUE TITLE
Pull request for support of new version of Siesta almost ready

### ISSUE THREAD

**Issue by albgar** [marvel-nccr/ansible-role-siesta#11]
In my fork (`albgar/ansible-role-siesta`) I have prepared a new version of the Siesta role that installs the MaX-1.1 version. The latest commit in master passes the CI checks for ubuntu18, but not for ubuntu16 (since this version does not have a fully featured libxc apt package). 
I just need a bit of help with the proper ansible way to deactivate libxc support (which is optional in Siesta) for ubuntu16. 
The relevant variable in `defaults/main.yml` is `libgridxc_libxc_incantation`, which should be empty for ubuntu16. Also, in `tasks/main.yml`, in the `apt` section, `libxc-dev` should be removed for ubuntu16.

**Comment by ltalirz** [comment]
@albgar the ubuntu version is available via the `ansible_distribution_version`, see e.g. [here](https://raymii.org/s/tutorials/Ansible_-_Only_if_on_specific_distribution_or_distribution_version.html)

You are welcome to fix the role for 16.04, but I'd probably be even more interested in adding support for 20.04 (support for 16.04 will end in April 2021 and we switched to 18.04 for Quantum Mobile a long time ago).
In order to add tests on 20.04, simply add it here: https://github.com/marvel-nccr/ansible-role-siesta/blob/master/.github/workflows/ci.yml#L30
